image:
  file: Dockerfile
tasks:
- init: >
    brew install cmake glibc gcc
- command: >
    mkdir --parents build &&
    cd build &&
    cmake ..
- command: >
    make &&
    ./tinyraytracer &&
    pnmtopng out.ppm > out.png &&
    open out.png
